[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  conditions = {X-Not-Found = "true"}

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200