[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Handle 404s first
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true
  conditions = {Response-Code = ["404"]}

# Then handle all other routes as SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true